---
on: [push, pull_request]
name: Konstruktoid Python linting
jobs:
  konstruktoidPythonlinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Konstruktoid Python linting
        uses: konstruktoid/action-pylint@master
