---
on: [push, pull_request]
name: Python linting
jobs:
  python-linting:
    name: Python linting
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Create UV venv
        run: uv venv .

      - name: Install requirements
        run: uv pip install -r requirements.txt

      - name: Konstruktoid Python linting
        uses: konstruktoid/action-pylint@master
